require("options")
require("keymaps")
require("lazynvim-init")
require("lsp")
-- colorscheme is set by github-theme plugin (see lua/plugins/plugin-github-theme.lua)
require("command")
require("core.autocmds")
